region: us-east-1

function_name: ustda_trade_leads
handler: service.handler
role: lambda_api
description: Fetches trade leads links from both XML and RSS feeds, combines them, builds a single JSON document, and stores it in S3
runtime: python3.8

timeout: 300
memory_size: 128
